FROM golang:1.22-alpine AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o /bin/report ./cmd/report

FROM alpine:3.20
COPY --from=build /bin/report /report
EXPOSE 8081
ENTRYPOINT ["/report"]
