services:
  kafka:
    image: bitnami/kafka:3.7
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    healthcheck:
      test: ["CMD", "bash", "-lc", "kafka-topics.sh --bootstrap-server kafka:9092 --list"]
      interval: 5s
      timeout: 5s
      retries: 20

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  api:
    build: ../services/api
    container_name: api
    environment:
      - KAFKA_BROKER=kafka:9092
      - KAFKA_TOPIC=events
      - HTTP_ADDR=:8080
    ports:
      - "8080:8080"
    depends_on:
      kafka:
        condition: service_healthy

  worker:
    build: ../services/worker
    container_name: worker
    environment:
      - KAFKA_BROKER=kafka:9092
      - KAFKA_TOPIC=events
      - KAFKA_GROUP=mini-worker
      - REDIS_ADDR=redis:6379
    depends_on:
      kafka:
        condition: service_healthy
      redis:
        condition: service_started

  stats:
    build: ../services/stats
    container_name: stats
    environment:
      - REDIS_ADDR=redis:6379
      - HTTP_ADDR=:8082
    ports:
      - "8082:8082"
    depends_on:
      redis:
        condition: service_started
